/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VinylResponse } from '../../models/vinyl-response';

export interface FindBookById$Params {
  'vinyl-id': number;
}

export function findBookById(http: HttpClient, rootUrl: string, params: FindBookById$Params, context?: HttpContext): Observable<StrictHttpResponse<VinylResponse>> {
  const rb = new RequestBuilder(rootUrl, findBookById.PATH, 'get');
  if (params) {
    rb.path('vinyl-id', params['vinyl-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VinylResponse>;
    })
  );
}

findBookById.PATH = '/vinyls/{vinyl-id}';
