/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BorrowedVinylsResponse {
  albumTitle?: string;
  artistName?: string;
  barcode?: string;
  id?: number;
  rate?: number;
  returnApproved?: boolean;
  returned?: boolean;
}
