/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BorrowedVinylsResponse } from '../models/borrowed-vinyls-response';
export interface PageResponseBorrowedVinylsResponse {
  content?: Array<BorrowedVinylsResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
