/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VinylResponse {
  albumTitle?: string;
  archived?: boolean;
  artistName?: string;
  barcode?: string;
  description?: string;
  id?: number;
  owner?: string;
  rate?: number;
  shareable?: boolean;
  vinylCoverImage?: string;
}
