/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VinylRequest {
  albumTitle: string;
  artistName: string;
  barcode: string;
  description: string;
  id?: number;
  shareable?: boolean;
}
