/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthenticateRequest } from './models/authenticate-request';
export type { AuthenticationResponse } from './models/authentication-response';
export type { BorrowedVinylsResponse } from './models/borrowed-vinyls-response';
export type { FeedbackRequest } from './models/feedback-request';
export type { FeedbackResponse } from './models/feedback-response';
export type { PageResponseBorrowedVinylsResponse } from './models/page-response-borrowed-vinyls-response';
export type { PageResponseFeedbackResponse } from './models/page-response-feedback-response';
export type { PageResponseVinylResponse } from './models/page-response-vinyl-response';
export type { RegistrationRequest } from './models/registration-request';
export type { VinylRequest } from './models/vinyl-request';
export type { VinylResponse } from './models/vinyl-response';
